// Collections behind /walton-hersham-fc-away-fans-guide/. See
// docs/away-fans-guide-plan.md, sections 3 and 7.
//
// Every practical fact is a `fact`: one of three shapes, and nothing else.
//
//   { value, source }             checked against a source on a stated date
//   { value, placeholder: true }  prototype data, shown on preview builds with
//                                 a visible marker; scripts/check-away-guide.mjs
//                                 fails a production build while any remain
//   { unconfirmed: { ask, question } }
//                                 a question for the club, a venue, an operator
//                                 or a site visit; renders nothing in production
//
// The third shape replaces the brief's to-do strings for unchecked facts,
// which the verification-marker check would (rightly) refuse to build.
import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const clock = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);

// checkedSource is passed in from content.config.ts so the guide uses the
// same source shape, and the same basis list, as the rest of the site.
export function awayGuideCollections(checkedSource: z.ZodTypeAny) {
  const unconfirmed = z.object({
    unconfirmed: z.object({
      ask: z.enum(['club', 'venue', 'operator', 'site-visit']),
      question: z.string(),
    }),
  });
  const fact = <T extends z.ZodTypeAny>(value: T) => z.union([
    z.object({ value, source: checkedSource }),
    z.object({ value, placeholder: z.literal(true) }),
    unconfirmed,
  ]);
  const text = fact(z.string());

  // One record: the ground and the answers the quick answers card needs.
  const ground = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/ground' }),
    schema: z.object({
      name: z.string(),
      address: text,
      postcode: text,
      officialSite: fact(z.string().url()),
      kickOffSaturday: text,
      kickOffMidweek: text,
      turnstilesOpen: text,
      tickets: text,
      prices: text,
      disabledSupporters: text,
      parking: text,
      accessibleParking: text,
      pitch: text,
      coveredSeating: text,
      segregation: text,
      awayEnd: text,
    }),
  });

  const routes = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/routes' }),
    schema: z.object({
      variant: z.enum(['road', 'towpath']),
      title: z.string(),
      order: z.number().int(),
      // One line of street names, for the print card.
      streets: z.string(),
      // Route-level: the step points and wording have not been walked yet.
      placeholder: z.boolean().default(false),
      bestFor: text,
      surface: text,
      lighting: text,
      stepFree: text,
      afterDark: text,
      steps: z.array(z.object({
        id: z.string().regex(/^[a-z0-9-]+$/),
        title: z.string(),
        text: z.string(),
        lat: z.number(),
        lng: z.number(),
        // Photo slot name, af-<chapter>-<subject>-<orientation>, from the shot list.
        photo: z.string().optional(),
        history: z.object({ href: z.string(), label: z.string() }).optional(),
        // Pubs passed on this stretch, in walking order. A link only where the
        // pub has a Directory listing.
        pubs: z.array(z.object({ name: z.string(), href: z.string().optional() })).default([]),
      })).min(2),
    }),
  });

  // Last departures from Walton-on-Thames, one record per day type and
  // direction. The finder hides itself once timetableValidTo has passed.
  const departures = z.object({
    times: z.array(clock).min(1),
    timetableValidFrom: isoDate,
    timetableValidTo: isoDate,
  });
  const trains = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/trains' }),
    schema: z.object({
      direction: z.enum(['London Waterloo', 'Woking']),
      dayType: z.enum(['saturday', 'weekday']),
      departures: z.union([
        departures.extend({ source: checkedSource }),
        departures.extend({ placeholder: z.literal(true) }),
      ]),
    }),
  });

  // A bus between the town centre and the ground. Research on 29 September
  // 2026 found no bus from Walton-on-Thames station to the ground: the 564
  // runs from Church Street in the town centre, so the walk between Church
  // Street and the station is part of the option, and is generated by the
  // map build rather than typed in here.
  const buses = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/buses' }),
    schema: z.object({
      route: text,
      operator: text,
      townStop: text,
      groundStop: text,
      // Departures from the town stop towards the ground, and from the ground
      // stop back towards the town, by day type.
      toGround: z.object({ saturday: fact(z.array(clock)), weekday: fact(z.array(clock)) }),
      fromGround: z.object({ saturday: fact(z.array(clock)), weekday: fact(z.array(clock)) }),
      toGroundMins: fact(z.number().int()),
      fromGroundMins: fact(z.number().int()),
      frequency: text,
      noService: text,
      timetableValidFrom: isoDate.optional(),
      timetableValidTo: isoDate.optional(),
      operatorUrl: fact(z.string().url()),
    }),
  });

  const taxis = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/taxis' }),
    schema: z.object({
      rankAtStation: text,
      rankLocation: text,
      pickupAtGround: text,
      rideHailing: z.array(z.object({ name: z.string(), note: text })).default([]),
      firms: z.array(z.object({
        name: z.string(),
        phone: z.string(),
        url: z.string().url().optional(),
        source: checkedSource,
      })).default([]),
    }),
  });

  // Pubs, food, supermarkets and hotels. Identity (name, address) is also in
  // the Directory where a listing exists; `business` links the two. Hours are
  // structured per day so the page can show "open now"; a venue whose hours
  // are not sourced shows no open or closed label.
  const day = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d-([01]\d|2[0-4]):[0-5]\d$/);
  const venues = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/venues' }),
    schema: z.object({
      name: z.string(),
      business: z.string().optional(),
      type: z.enum(['pub', 'grab-and-go', 'sit-down', 'supermarket', 'hotel']),
      // Walking routes the venue is on, and its order along them.
      routes: z.array(z.enum(['road', 'towpath'])).default([]),
      order: z.number().default(99),
      area: z.enum(['route', 'town-centre', 'ground', 'station']),
      lat: z.number(),
      lng: z.number(),
      pointBasis: z.string(),
      address: text,
      url: fact(z.string().url()).optional(),
      phone: text.optional(),
      hours: fact(z.object({
        mon: day, tue: day, wed: day, thu: day, fri: day, sat: day, sun: day,
      })).optional(),
      hoursLabel: z.string().default('Opening hours'),
      features: z.array(z.object({ label: z.string(), f: text })).default([]),
      featured: z.boolean().default(false),
    }),
  });

  // Club history for groundhoppers, and the practical and safety block.
  const info = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/info' }),
    schema: z.object({
      history: z.array(z.object({ year: z.string(), f: text })),
      nickname: text,
      aAndE: text,
      police: text,
    }),
  });

  // FAQs. Answers may contain {{tokens}} filled from the guide's sourced data
  // when the page builds, so an answer cannot drift from the page. A question
  // whose token has no confirmed value is left out in production.
  const faqs = defineCollection({
    loader: glob({ pattern: '*.{yaml,yml}', base: './src/content/away-guide/faqs' }),
    schema: z.object({
      items: z.array(z.object({ q: z.string(), a: z.string() })).min(1),
    }),
  });

  return {
    'away-info': info,
    'away-faqs': faqs,
    'away-venues': venues,
    'away-ground': ground,
    'away-routes': routes,
    'away-trains': trains,
    'away-buses': buses,
    'away-taxis': taxis,
  };
}
